### ISSUE TITLE
Support for Credentials with X.509 Authentication

### ISSUE THREAD

**Issue by jon-opal** [hashicorp/vault-plugin-database-mongodbatlas#35]
Thank you for this wonderful plugin!

Currently, there is support for generating credentials for username/passwords for SCRAM authentication.

I am wondering if there is a plan to support the generation of credentials with X.509 certificates, for example using certificates that I manually upload to Atlas (https://docs.atlas.mongodb.com/security-self-managed-x509/)

**Comment by themantissa** [comment]
@jon-opal I'm from MongoDB and am glad you are happy with the plugin!  We do not currently have plans to support x509 but we take customer input seriously.  Please feel free to file a product suggestion [here](https://feedback.mongodb.com/forums/924145-atlas?category_id=382936) and we'll consider it as we move forward.

**Comment by swenson** [comment]
Thanks for this issue. Supporting X.509 does seem possible via [this Atlas API](https://www.mongodb.com/docs/atlas/reference/api/x509-configuration/), so it is certainly something that could be added in the future, but I don't know of any specific plans to.

@themantissa I'm not sure what you mean -- it looks like there is an API for this already on the MongoDB Atlas side?

**Comment by themantissa** [comment]
@swenson I should have been more specific, let me amend the statement "We do not currently have plans to support x509  **with the MongoDB Atlas Database Secret Engine**".   Yes, it is supported in the platform and support is available via API - but not near term plans to support within Vault.

**Comment by swenson** [comment]
@themantissa Ah, got it. Thanks for the context!
