### ISSUE TITLE
Support for Ops Manager/Cloud Manager

### ISSUE THREAD

**Issue by Freyert** [hashicorp/vault-plugin-database-mongodbatlas#37]
Hello! I don't know how possible this is, but I find myself in a situation where I am a user of Atlas, _and_ Ops Manager. I've seen that the APIs are fairly similar but this plugin doesn't work with Ops Manager so I would need to do a lot of leg work to get this working with the plain MongoDB Database Plugin.

Are there any plans to make this compatible with Ops Manager as well?

**Comment by themantissa** [comment]
Hi @Freyert - I'm in Product at MongoDB and we do not have any plans to extend Vault SE coverage to Ops Manager or Cloud Manager.

**Comment by Zuhairahmed** [comment]
Given this is more of a feature request feel free to share feedback on our UserVoice portal or upvote an existing item. Happy to continue share feedback there. https://feedback.mongodb.com/forums/924145-atlas?category_id=382936 

Resolving this issue, feel free to create a new issue in case if you need anything else. Thank you

**Comment by Freyert** [comment]
As an update, we've moved away from using this backend for DB credential management on this issue and https://github.com/hashicorp/vault-plugin-database-mongodbatlas/issues/10#issuecomment-962279474.

I really applaud the Atlas and MongoDB team in general for championing the much more accessible OIDC based authentication. We're looking forward to using it.

Would love the same for the Atlas API as well though.

**Comment by themantissa** [comment]
Thank you for the heads up @Freyert!  FYI, we are indeed working to modernize authentication across the board and you can expect changes coming to the Atlas Admin API as well.
