### ISSUE TITLE
Same commit SHA on two releases

### ISSUE THREAD

**Issue by MarcelMue** [hashicorp/vault-plugin-database-mongodbatlas#8]
Hello friends :wave:
We ran into an interesting issue with this repository. For `0.1.0` and `0.1.1` the same commit was used. This suggests that git history was rewritten between the two releases https://github.com/hashicorp/vault-plugin-database-mongodbatlas/releases .

For us this causes problems with `go modules` as we initially imported `0.1.0` and therefor had this reference in our `go.sum`. Now that the git history was likely rewritten we get the following error:
```
verifying github.com/hashicorp/vault-plugin-database-mongodbatlas@v0.1.0/go.mod: checksum mismatch
	downloaded: h1:MP3kfr0N+7miOTZFwKv952b9VkXM4S2Q6YtQCiNKWq8=
	go.sum:     h1:HTXNzFr/SAVtJOs7jz0XxZ69jlKtaceEwp37l86UAQ0=SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.For more information, see 'go help module-auth'.
```

This can be fixed by simply moving to `0.1.1` but caused us to waste a significant amount of time in order to figure out what the issue was.

I don't believe this can be easily fixed now - but please do not perform magic like this in the future.

cc @kalafut

**Comment by kalafut** [comment]
@MarcelMue A tooling error early in beta resulted in the official Go module proxy (proxy.golang.org) caching an incorrect version. Most devs had the correct version locally so this wasn't detected until much later. You can work around the current issue by setting the environment variable `GOPROXY=direct` before your build to pull directly from our repos and not the module proxy.

We'll be adding some additional verification to avoid this type of issue in the future. Sorry for the inconvenience.

**Comment by MarcelMue** [comment]
Okay, works for me.
